#!/usr/bin/env python2

from OpenGL.GL import *
from OpenGL.GLUT import *

def main():
    glutInit()
    glutInitDisplayMode(GLUT_RGBA | GLUT_DOUBLE | GLUT_DEPTH)
    glutCreateWindow("Annotation")
    glutDisplayFunc(display)
    glClearColor(0.5, 0.5, 0.5, 1.0)
    glutMainLoop()

def display():
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
    glutSwapBuffers()

if __name__ == "__main__":
    main()
