#!/usr/bin/env python2

import numpy
from OpenGL.GL import *
from OpenGL.GLUT import *

def main():
    glutInit()
    glutInitDisplayMode(GLUT_RGBA | GLUT_DOUBLE | GLUT_DEPTH)
    glutCreateWindow("Annotation")
    glutDisplayFunc(render)
    glClearColor(0.2, 0.2, 0.2, 1.0)
    glutMainLoop()

def render():
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)

    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    glOrtho(0.0, 1.0, 0.0, 1.0, -1.0, 1.0)

    glColor(1.0, 0.0, 0.0)
    glPointSize(5.0)

    vertexBuffer = glGenBuffers(1)
    glBindBuffer(GL_ARRAY_BUFFER, vertexBuffer)
    glBufferData(GL_ARRAY_BUFFER, 12 * 4, numpy.array([
            0.25, 0.25, 0.0,
            0.75, 0.25, 0.0,
            0.75, 0.75, 0.0,
            0.25, 0.75, 0.0
        ], numpy.float32), GL_STATIC_DRAW)

    glEnableClientState(GL_VERTEX_ARRAY)
    glVertexPointer(3, GL_FLOAT, 0, None)
    glDrawArrays(GL_POINTS, 0, 4)
    glDisableClientState(GL_VERTEX_ARRAY)

    glDeleteBuffers(1, [vertexBuffer])

    glFlush()
    glutSwapBuffers()

if __name__ == "__main__":
    main()
